version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@vue/compiler-sfc"
    versions:
    - 3.0.5
    - 3.0.6
  - dependency-name: "@mdi/js"
    versions:
    - 5.9.55
  - dependency-name: node-notifier
    versions:
    - 8.0.1
